src/main/java/com/bionic/sschudakov/web/CartBean.java
package com.bionic.sschudakov.web;

import com.bionic.sschudakov.dao.DishPriceDao;
import com.bionic.sschudakov.entity.Dish;
import com.bionic.sschudakov.entity.DishPrice;
import com.bionic.sschudakov.entity.OrderItem;
import com.bionic.sschudakov.entity.RestaurantOrder;
import com.bionic.sschudakov.service.OrderItemService;
import com.bionic.sschudakov.service.RestaurantOrderService;
import org.springframework.context.annotation.Scope;

import javax.inject.Inject;
import javax.inject.Named;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.*;

/**
 * Created by Sergey on 09.07.14.
 */
@Named
@Scope("session")
public class CartBean {

    @Inject
    private DishPriceDao dishPriceDao;

    private Date orderOpenDate;
    private List<CartItem> cartItems = new ArrayList<CartItem>();

    private String clientsPhoneNumber = "";

    public CartBean() {
        orderOpenDate = new Date();
    }

    public Date getOrderOpenDate() {
        return orderOpenDate;
    }

    public List<CartItem> getCartItems() {
        return cartItems;
    }


    public String getClientsPhoneNumber() {
        return clientsPhoneNumber;
    }

    public void setClientsPhoneNumber(String clientsPhoneNumber) {
        this.clientsPhoneNumber = clientsPhoneNumber;
    }

    public String add(Dish dish) {

        boolean newDish = true;

        for (CartItem c : cartItems) {

            if (c.getDish().getId() == dish.getId()) {
                c.setQuantity(c.getQuantity() + 1);
                newDish = false;
                break;
            }
        }

        if (newDish) {
            CartItem cartItem = new CartItem();
            cartItem.setDish(dish);
            DishPrice dishPrice = dishPriceDao.findLastActualDishPrice(dish, orderOpenDate);
            Integer price = 0;
            if (dishPrice != null) {
                price = dishPrice.getPrice();
            }
            cartItem.setPrice(price);
            cartItem.setQuantity(new Integer(1));
            cartItems.add(cartItem);
        }

        return "";

    }

    public String remove(Dish dish) {
        for (Iterator<CartItem> it = cartItems.iterator(); it.hasNext(); ) {
            CartItem cartItem = it.next();
            if (cartItem.getDish().getId() == dish.getId()) {
                cartItem.setQuantity(cartItem.getQuantity() - 1);
                if (cartItem.getQuantity().equals(new Integer(0))) {
                    it.remove();
                }
            }
        }

        return "";
    }

    public int getCartCount() {

        int cartSize = 0;

        for (CartItem c : cartItems) {
            cartSize += c.getQuantity();
        }

        return cartSize;

    }

    public BigDecimal getCartTotalPrice() {

        Long cartPrice = 0L;
        for (CartItem c : cartItems) {
            cartPrice += (c.getQuantity() * c.getPrice());
        }

        return new BigDecimal(cartPrice).divide(new BigDecimal(100));
    }

    public String cleanCart() {
        this.cartItems = new ArrayList<CartItem>();
        return "menu";
    }

    /**
     * Method to check whether dish item has been already put to the cart.
     *
     * @param dishId
     * @return
     */
    public boolean cartHasItem(Long dishId) {

        for (CartItem c : cartItems) {
            if (c.getDish().getId().equals(dishId)) {
                return true;
            }
        }

        return false;
    }

    public int getCartItemCount(Long id) {

        int cartItemCount = 0;

        for (CartItem c : cartItems) {
            if (c.getDish().getId().equals(id))
                cartItemCount += c.getQuantity();
        }

        return cartItemCount;

    }

}

src/main/java/com/bionic/sschudakov/web/DishBean.java
package com.bionic.sschudakov.web;

import com.bionic.sschudakov.entity.Dish;
import com.bionic.sschudakov.entity.DishPrice;
import com.bionic.sschudakov.entity.FoodCategory;
import com.bionic.sschudakov.service.DishPriceService;
import com.bionic.sschudakov.service.DishService;
import com.bionic.sschudakov.service.FoodCategoryService;
import org.springframework.context.annotation.Scope;

import javax.annotation.PostConstruct;
import javax.faces.component.html.HtmlDataTable;
import javax.faces.component.html.HtmlInputHidden;
import javax.inject.Inject;
import javax.inject.Named;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

@Named
@Scope("session")
public class DishBean {

    @Inject
    private DishService dishService;

    @Inject
    private DishPriceService dishPriceService;

    @Inject
    FoodCategoryService foodCategoryService;

    @Inject
    CartBean cartBean;

    /**
     * Fields to create new dish entity.
     */
    private FoodCategory foodCategory;
    private String name;
    private String description;
    private boolean kitchenMade;


    private List<Dish> dishesByFoodCategory;
    private Dish currentDish;
    private FoodCategory currentFoodCategory;

    private List<Dish> allDishes;
    private boolean updateNeeded = true;

    /**
     * Fields needed to edit single dish information.
     */
    private HtmlDataTable dataTable;
    private Dish dataItem = new Dish();
    private HtmlInputHidden dataItemId = new HtmlInputHidden();

    // Actions -----------------------------------------------------------------------------------
    public String editDataItem() {
        // Get selected Dish item to be edited.
        dataItem = (Dish) dataTable.getRowData();

        // Store the ID of the data item in hidden input element.
        dataItemId.setValue(dataItem.getId());

        return "set_new_dish_price"; //Navigation
    }

    public String saveDataItem() {

        // Retain the ID of the data item from hidden input element.
        dataItem.setId(Long.valueOf(dataItemId.getValue().toString()));

        // Save Dish.
        dishService.update(dataItem);

        return "set_dish_prices";
    }

    // Getters -----------------------------------------------------------------------------------

    public HtmlDataTable getDataTable() {
        return dataTable;
    }

    public Dish getDataItem() {
        return dataItem;
    }

    public HtmlInputHidden getDataItemId() {
        return dataItemId;
    }

    // Setters -----------------------------------------------------------------------------------

    public void setDataTable(HtmlDataTable dataTable) {
        this.dataTable = dataTable;
    }

    public void setDataItem(Dish dataItem) {
        this.dataItem = dataItem;
    }

    public void setDataItemId(HtmlInputHidden dataItemId) {
        this.dataItemId = dataItemId;
    }





    @PostConstruct
    private void init() {
        currentFoodCategory = foodCategoryService.findById(1L);
        dishesByFoodCategory = dishService.findByCategoryId(1L);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public FoodCategory getFoodCategory() {
        return foodCategory;
    }

    public void setFoodCategory(FoodCategory foodCategory) {
        this.foodCategory = foodCategory;
    }

    public boolean isKitchenMade() {
        return kitchenMade;
    }

    public void setKitchenMade(boolean kitchenMade) {
        this.kitchenMade = kitchenMade;
    }


    public List<Dish> getAllDishes() {
        if (updateNeeded) {
            allDishes = dishService.getAll();
            updateNeeded = false;
        }
        return allDishes;
    }

    public void setAllDishes(List<Dish> allDishes) {
        this.allDishes = allDishes;
    }

    public Dish getCurrentDish() {
        return currentDish;
    }

    public FoodCategory getCurrentFoodCategory() {
        return currentFoodCategory;
    }

    public List<Dish> getDishesByFoodCategory() {
        return dishesByFoodCategory;
    }

    public String getDishDetails(Long dishId) {
        this.currentDish = dishService.getById(dishId);
        return "dish_item";
    }

    public BigDecimal getCurrentDishPrice() {
        DishPrice dishPrice = dishPriceService.getLastActualDishPrice(currentDish, new Date());
        if (dishPrice != null) {
            Integer price = dishPrice.getPrice();
            return new BigDecimal(price).divide(new BigDecimal(100));
        }
        return BigDecimal.ZERO;
    }

    public void changeFoodCategory(Long currentFoodCategoryId) {
        currentFoodCategory = foodCategoryService.findById(currentFoodCategoryId);
        dishesByFoodCategory = dishService.findByCategoryId(currentFoodCategoryId);
    }

    public void addToCart(Long dishId) {
        cartBean.add(dishService.getById(dishId));
    }

    public BigDecimal getDishPrice(Long dishId) {
        Dish dish = dishService.getById(dishId);
        DishPrice dishPrice = dishPriceService.getLastActualDishPrice(dish, new Date());
        if (dishPrice != null) {
            Integer price = dishPrice.getPrice();
            return new BigDecimal(price).divide(new BigDecimal(100));
        }
        return BigDecimal.ZERO;
    }

    public String loadPageByFoodCategoryId(Long foodCategoryId) {
        currentFoodCategory = foodCategoryService.findById(foodCategoryId);
        dishesByFoodCategory = dishService.findByCategoryId(foodCategoryId);
        return "menu";
    }

    public List<Dish> getAll() {
        return dishService.getAll();
    }

    public String editAction(Dish dish) {
        dish.setEditable(true);
        return null;
    }

    public String delete(Long dishId) {
        dishService.delete(dishId);
        updateNeeded = true;
        return "";
    }

    public String createDish() {
        dishService.createDish(null, name, description, kitchenMade);
        name = null;
        description = null;
        kitchenMade = false;
        updateNeeded = true;
        return "";
    }

    public String saveAction() {
        for (Dish d : allDishes) {
            if (d.isEditable()) {
                dishService.update(d);
            }
        }
        updateNeeded = true;
        return null;
    }
}

src/main/java/com/bionic/sschudakov/web/LoginBean.java
package com.bionic.sschudakov.web;

import com.bionic.sschudakov.dao.DishPriceDao;
import com.bionic.sschudakov.entity.Dish;
import com.bionic.sschudakov.entity.DishPrice;
import com.bionic.sschudakov.entity.User;
import com.bionic.sschudakov.service.UserService;
import org.springframework.context.annotation.Scope;

import javax.inject.Inject;
import javax.inject.Named;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

/**
 * Created by Sergey on 09.07.14.
 */
@Named
@Scope("session")
public class LoginBean {

    @Inject
    UserService userService;

    private String userName;
    private String password;

    public boolean isLogged = false;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String processLogin() {
        User user = userService.findUser(userName);

        if (user == null || !user.getPassword().equals(password)) {
            return "bad_credentials";
        }
        isLogged = true;
        return "admin_home";
    }


}

src/main/java/com/bionic/sschudakov/web/OrderItemBean.java
package com.bionic.sschudakov.web;

import com.bionic.sschudakov.entity.OrderItem;
import com.bionic.sschudakov.service.OrderItemService;
import org.springframework.context.annotation.Scope;

import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.IOException;
import java.util.List;

/**
 * Created by Sergey on 09.07.14.
 */
@Named
@Scope("request")
public class OrderItemBean {

    @Inject
    OrderItemService orderItemService;

    @Inject
    CartBean cartBean;

    public List<OrderItem> getOrderItems() {
        return orderItemService.getAllOrderItems();
    }

    public String getQuery() {
        return FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("query");
    }

    public void checkIfQueryExists() throws IOException {
        if (orderItemService.getOrderItemById(Long.parseLong(getQuery())) == null) {
            FacesContext.getCurrentInstance().getExternalContext().redirect("error.xhtml");
        }
    }

    public OrderItem getOrderItemById() {
         return orderItemService.getOrderItemById(Long.parseLong(getQuery()));
    }

//    public void addToCart() {
//        String query = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("query");
//        cartBean.add(orderItemService.getOrderItemById(Long.parseLong(query)));
//    }

}

src/main/webapp/e-kafe/secured/admin_home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsf/composite"
                xmlns:o="http://openfaces.org/"
                xmlns:t="http://myfaces.apache.org/tomahawk"
                template="${request.contextPath}/e-kafe/templates/general_admin.xhtml">

    <ui:define name="title"><h:outputText value="Welcome to E-kafe"/></ui:define>
    <ui:define name="header">
        <t:div styleClass="ekafe">
            <h:outputText value="E-kafe"/>
        </t:div>
        <t:div styleClass="headerText">
            <h:outputText value="Admin Menu Panel"/>
        </t:div>
        <t:div styleClass="loginStatus">
            <h:graphicImage library="images" name="unlocked.png" styleClass="unlockImg"/>
        </t:div>
    </ui:define>


    <ui:define name="content">
        <t:div styleClass="centeredText">
            <h:form>
                <h:outputText value="Current Orders:" style="font-size: 24px; font-weight: bolder"/>
                <o:dataTable var="orderItem"
                             value="#{orderItemBean.orderItems}"
                             rowKey="#{orderItem.id}"
                             style="margin: 0 auto">
                    <o:column>
                        <f:facet name="header">
                            <h:outputText value="Order Date/Time"/>
                        </f:facet>
                        <h:outputText value="#{orderItem.restaurantOrder.dateTimeSubmit}">
                            <f:convertDateTime pattern="dd.MM.yyyy HH:mm"/>
                        </h:outputText>
                    </o:column>
                    <o:column>
                        <f:facet name="header">
                            <h:outputText value="Dish"/>
                        </f:facet>
                        <h:outputText value="#{orderItem.dish.name}"/>
                    </o:column>
                    <o:column>
                        <f:facet name="header">
                            <h:outputText value="Quantity"/>
                        </f:facet>
                        <h:outputText value="#{orderItem.quantity}"/>
                    </o:column>
                    <o:column>
                        <f:facet name="header">
                            <h:outputText value="Dish Price"/>
                        </f:facet>
                        <h:outputText value="#{orderItem.dishPrice}">
                            <f:convertNumber pattern="#0.00"/>
                        </h:outputText>
                    </o:column>
                    <o:column>
                        <f:facet name="header">
                            <h:outputText value="Total"/>
                        </f:facet>
                        <h:outputText value="#{orderItem.quantity * orderItem.dishPrice}">
                            <f:convertNumber pattern="#0.00"/>
                        </h:outputText>
                    </o:column>
                </o:dataTable><br/><br/>
            </h:form>
        </t:div>
    </ui:define>
</ui:composition>

src/main/webapp/e-kafe/secured/bad_credentials.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsf/composite"
                xmlns:o="http://openfaces.org/"
                xmlns:t="http://myfaces.apache.org/tomahawk"
                template="${request.contextPath}/e-kafe/templates/general_admin.general_login.xhtml">

    <ui:define name="title"><h:outputText value="Welcome to E-kafe"/></ui:define>
    <ui:define name="header">
        <t:div styleClass="ekafe">
            <h:outputText value="E-kafe"/>
        </t:div>
        <t:div styleClass="headerText">
            <h:outputText value="Staff"/>
        </t:div>
        <t:div styleClass="shoppingCart">
            <h:graphicImage library="images" name="white_padlock.png" style="height: 100px; width: auto"/>
        </t:div>
    </ui:define>


    <ui:define name="content">
        <t:div styleClass="centeredText">
            <h:form id="loginForm" style="padding: 20px 0">
                <h:panelGrid columns="3">
                    <h:outputText value="Sorry, Username or Password is incorrect!" /><br/><br/>
                    <h:outputText value="Please try again." /><br/><br/>
                    <h:commandButton value="Back to login" action="login" />
                </h:panelGrid>
            </h:form>
        </t:div>
    </ui:define>
</ui:composition>

src/main/webapp/e-kafe/secured/edit_dishes.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsf/composite"
                xmlns:o="http://openfaces.org/"
                xmlns:t="http://myfaces.apache.org/tomahawk"
                template="${request.contextPath}/e-kafe/templates/general_admin.xhtml">

    <ui:define name="title"><h:outputText value="Edit Dishes"/></ui:define>
    <ui:define name="header">
        <t:div styleClass="ekafe">
            <h:outputText value="E-kafe"/>
        </t:div>
        <t:div styleClass="headerText">
            <h:outputText value="Edit Dishes"/>
        </t:div>
        <t:div styleClass="loginStatus">
            <h:graphicImage library="images" name="unlocked.png" styleClass="unlockImg"/>
        </t:div>
    </ui:define>


    <ui:define name="content">
        <t:div styleClass="centeredText">
            <h:form>
                <h:outputText value="Dishes:" style="font-size: 24px; font-weight: bolder"/>
                <o:dataTable var="dish"
                             value="#{dishBean.allDishes}"
                             rowKey="#{dish.id}"
                             style="margin: 0 auto">
                    <o:column>
                        <f:facet name="header">
                            <h:outputText value="Name"/>
                        </f:facet>
                        <h:inputText value="#{dish.name}" size="12" rendered="#{dish.editable}"/>
                        <h:outputText value="#{dish.name}" rendered="#{not dish.editable}"/>
                    </o:column>
                    <o:column>
                        <f:facet name="header">
                            <h:outputText value="Description"/>
                        </f:facet>
                        <h:inputTextarea value="#{dish.description}" size="10" rendered="#{dish.editable}"/>
                        <h:outputText value="#{dish.description}" rendered="#{not dish.editable}"/>
                    </o:column>
                    <o:column>
                        <f:facet name="header">
                            <h:outputText value="Actions"/>
                        </f:facet>
                        <h:panelGroup id="foodCategoryActions">
                            <h:commandButton value="Edit" action="#{dishBean.editAction(dish)}"
                                             rendered="#{not dish.editable}"/>
                            <h:commandButton value="Delete" action="#{dishBean.delete(dish.id)}"/>
                        </h:panelGroup>
                    </o:column>
                </o:dataTable><br/><br/>
                <h:commandButton value="Save Changes" action="#{dishBean.saveAction}"/><br/><br/><br/>
            </h:form>

            <h:form>
                <h:outputText value="Add New Dish:" style="font-size: 24px; font-weight: bolder"/>
                <h:panelGrid id="addPanelGrid" columns="2" style="margin: 0 auto">
                    <h:panelGroup>
                        <h:outputText value="Name:"/>
                        <h:outputText style="color:red" value="*  "/>
                    </h:panelGroup>
                    <o:inputText id="name"
                                 value="#{dishBean.name}"
                                 required="true"
                                 style="background: beige; border: 2px solid brown; color: brown; font-weight: bold;"
                                 promptText="Dish Name"
                                 promptTextStyle="font-style: italic; color: #7e7e7e;"
                                 focusedStyle="border: 2px solid orange;">
                        <f:validateLength minimum="2"/>
                    </o:inputText>
                    <h:panelGroup>
                        <h:outputText value="Description:"/>
                        <h:outputText value="   "/>
                    </h:panelGroup>
                    <o:inputText id="description"
                                 value="#{dishBean.description}"
                                 style="background: beige; border: 2px solid brown; color: brown; font-weight: bold;"
                                 promptText="Dish Description"
                                 promptTextStyle="font-style: italic; color: #7e7e7e;"
                                 focusedStyle="border: 2px solid orange;">
                        <f:validateLength minimum="2"/>
                    </o:inputText>
                    <h:panelGroup>
                        <h:outputText value="Made By Kitchen:"/>
                        <h:outputText value="   "/>
                    </h:panelGroup>
                    <o:selectBooleanCheckbox value="#{dishBean.kitchenMade}">
                        <h:outputText value="Made by Kitchen"/>
                    </o:selectBooleanCheckbox><br/>
                    <o:commandButton id="createNewDishBtn" action="#{dishBean.createDish}"
                                     value="Create"
                                     style="margin-top: 10px"/>

                </h:panelGrid>
            </h:form>
        </t:div>
    </ui:define>
</ui:composition>

src/main/webapp/e-kafe/secured/edit_food_categories.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsf/composite"
                xmlns:o="http://openfaces.org/"
                xmlns:t="http://myfaces.apache.org/tomahawk"
                template="${request.contextPath}/e-kafe/templates/general.xhtml">

    <ui:define name="title"><h:outputText value="Welcome to E-kafe"/></ui:define>
    <ui:define name="header">
        <t:div styleClass="ekafe">
            <h:outputText value="E-kafe"/>
        </t:div>
        <t:div styleClass="headerText">
            <h:outputText value="Our menu"/>
        </t:div>
        <t:div styleClass="shoppingCart">
            <h:form id="headerCartInfo">
                <h:panelGrid columns="2">
                    <h:commandLink action="cart" styleClass="textLnk">
                        <h:graphicImage library="images" name="shopping_cart.png"/>
                    </h:commandLink>
                    <h:commandLink action="cart" styleClass="textLnk">
                        <h:panelGroup>
                            <h:outputText id="cartSizeHeader" value="#{cartBean.cartCount} item(s)"/><br/>
                            <h:outputText id="cartTotalPriceHeader" value="#{cartBean.cartTotalPrice} UAH">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText><br/>
                        </h:panelGroup></h:commandLink>
                </h:panelGrid>
            </h:form>
        </t:div>
    </ui:define>


    <ui:define name="content">
        <h:panelGrid columns="3">
            <h:outputLabel value="Username"/>
            <h:inputText value="" required="true" requiredMessage="Please, enter your username" id="userNameInput"></h:inputText>
        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/e-kafe/secured/logout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsf/composite"
                xmlns:o="http://openfaces.org/"
                xmlns:t="http://myfaces.apache.org/tomahawk"
                template="${request.contextPath}/e-kafe/templates/general_admin.general_login.xhtml">

    <ui:define name="title"><h:outputText value="Welcome to E-kafe"/></ui:define>
    <ui:define name="header"></ui:define>
    <ui:define name="content"></ui:define>

</ui:composition>

src/main/webapp/e-kafe/secured/set_dish_prices.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsf/composite"
                xmlns:o="http://openfaces.org/"
                xmlns:t="http://myfaces.apache.org/tomahawk"
                template="${request.contextPath}/e-kafe/templates/general_admin.xhtml">

    <ui:define name="title"><h:outputText value="Welcome to E-kafe"/></ui:define>
    <ui:define name="header">
        <t:div styleClass="ekafe">
            <h:outputText value="E-kafe"/>
        </t:div>
        <t:div styleClass="headerText">
            <h:outputText value="Set Dish Prices"/>
        </t:div>
        <t:div styleClass="loginStatus">
            <h:graphicImage library="images" name="unlocked.png" styleClass="unlockImg"/>
        </t:div>
    </ui:define>


    <ui:define name="content">
        <t:div styleClass="centeredText">
            <h:outputText value="Dish Prices Management" style="font-weight: bold; font-size: 28px"/><br/><br/>
            <h:form>
                <h:dataTable binding="#{dishBean.dataTable}"
                             var="dish"
                             value="#{dishBean.all}"
                             styleClass="centeredTable">
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Food Category"/>
                        </f:facet>
                        <h:outputText value="#{dish.foodCategory.name}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Name"/>
                        </f:facet>
                        <h:outputText value="#{dish.name}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Dish Price"/>
                        </f:facet>
                        <h:outputText value="#{dishPriceBean.getLastActualDishPriceValue(dish)}">
                            <f:convertNumber pattern="#0.00"/>
                        </h:outputText>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Date/Time"/>
                        </f:facet>
                        <h:outputText value="#{dishPriceBean.getLastActualDishPriceDate(dish)}">
                            <f:convertDateTime pattern="yyyy-MM-dd HH:mm"/>
                        </h:outputText>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Action"/>
                        </f:facet>
                        <h:commandLink value="Edit" action="#{dishBean.editDataItem}"/>
                    </h:column>
                </h:dataTable>
            </h:form>
        </t:div>
    </ui:define>
</ui:composition>