src/main/java/com/bionic/sschudakov/web/CartBean.java
package com.bionic.sschudakov.web;

import com.bionic.sschudakov.dao.DishPriceDao;
import com.bionic.sschudakov.entity.Dish;
import com.bionic.sschudakov.entity.DishPrice;
import com.bionic.sschudakov.entity.OrderItem;
import com.bionic.sschudakov.entity.RestaurantOrder;
import com.bionic.sschudakov.service.OrderItemService;
import com.bionic.sschudakov.service.RestaurantOrderService;
import org.springframework.context.annotation.Scope;

import javax.inject.Inject;
import javax.inject.Named;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.*;

/**
 * Created by Sergey on 09.07.14.
 */
@Named
@Scope("session")
public class CartBean {

    @Inject
    private DishPriceDao dishPriceDao;

    private Date orderOpenDate;
    private List<CartItem> cartItems = new ArrayList<CartItem>();

    private String clientsPhoneNumber = "";

    public CartBean() {
        orderOpenDate = new Date();
    }

    public Date getOrderOpenDate() {
        return orderOpenDate;
    }

    public List<CartItem> getCartItems() {
        return cartItems;
    }


    public String getClientsPhoneNumber() {
        return clientsPhoneNumber;
    }

    public void setClientsPhoneNumber(String clientsPhoneNumber) {
        this.clientsPhoneNumber = clientsPhoneNumber;
    }

    public String add(Dish dish) {

        boolean newDish = true;

        for (CartItem c : cartItems) {

            if (c.getDish().getId() == dish.getId()) {
                c.setQuantity(c.getQuantity() + 1);
                newDish = false;
                break;
            }
        }

        if (newDish) {
            CartItem cartItem = new CartItem();
            cartItem.setDish(dish);
            DishPrice dishPrice = dishPriceDao.findLastActualDishPrice(dish, orderOpenDate);
            Integer price = 0;
            if (dishPrice != null) {
                price = dishPrice.getPrice();
            }
            cartItem.setPrice(price);
            cartItem.setQuantity(new Integer(1));
            cartItems.add(cartItem);
        }

        return "";

    }

    public String remove(Dish dish) {
        for (Iterator<CartItem> it = cartItems.iterator(); it.hasNext(); ) {
            CartItem cartItem = it.next();
            if (cartItem.getDish().getId() == dish.getId()) {
                cartItem.setQuantity(cartItem.getQuantity() - 1);
                if (cartItem.getQuantity().equals(new Integer(0))) {
                    it.remove();
                }
            }
        }

        return "";
    }

    public int getCartCount() {

        int cartSize = 0;

        for (CartItem c : cartItems) {
            cartSize += c.getQuantity();
        }

        return cartSize;

    }

    public BigDecimal getCartTotalPrice() {

        Long cartPrice = 0L;
        for (CartItem c : cartItems) {
            cartPrice += (c.getQuantity() * c.getPrice());
        }

        return new BigDecimal(cartPrice).divide(new BigDecimal(100));
    }

    public String cleanCart() {
        this.cartItems = new ArrayList<CartItem>();
        return "menu";
    }

    /**
     * Method to check whether dish item has been already put to the cart.
     *
     * @param dishId
     * @return
     */
    public boolean cartHasItem(Long dishId) {

        for (CartItem c : cartItems) {
            if (c.getDish().getId().equals(dishId)) {
                return true;
            }
        }

        return false;
    }

    public int getCartItemCount(Long id) {

        int cartItemCount = 0;

        for (CartItem c : cartItems) {
            if (c.getDish().getId().equals(id))
                cartItemCount += c.getQuantity();
        }

        return cartItemCount;

    }

}

src/main/java/com/bionic/sschudakov/web/DishBean.java
package com.bionic.sschudakov.web;

import com.bionic.sschudakov.entity.Dish;
import com.bionic.sschudakov.entity.DishPrice;
import com.bionic.sschudakov.entity.FoodCategory;
import com.bionic.sschudakov.service.DishPriceService;
import com.bionic.sschudakov.service.DishService;
import com.bionic.sschudakov.service.FoodCategoryService;
import org.springframework.context.annotation.Scope;

import javax.annotation.PostConstruct;
import javax.faces.component.html.HtmlDataTable;
import javax.faces.component.html.HtmlInputHidden;
import javax.inject.Inject;
import javax.inject.Named;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

@Named
@Scope("session")
public class DishBean {

    @Inject
    private DishService dishService;

    @Inject
    private DishPriceService dishPriceService;

    @Inject
    FoodCategoryService foodCategoryService;

    @Inject
    CartBean cartBean;

    /**
     * Fields to create new dish entity.
     */
    private FoodCategory foodCategory;
    private String name;
    private String description;
    private boolean kitchenMade;


    private List<Dish> dishesByFoodCategory;
    private Dish currentDish;
    private FoodCategory currentFoodCategory;

    private List<Dish> allDishes;
    private boolean updateNeeded = true;

    /**
     * Fields needed to edit single dish information.
     */
    private HtmlDataTable dataTable;
    private Dish dataItem = new Dish();
    private HtmlInputHidden dataItemId = new HtmlInputHidden();

    // Actions -----------------------------------------------------------------------------------
    public String editDataItem() {
        // Get selected Dish item to be edited.
        dataItem = (Dish) dataTable.getRowData();

        // Store the ID of the data item in hidden input element.
        dataItemId.setValue(dataItem.getId());

        return "set_new_dish_price"; //Navigation
    }

    public String saveDataItem() {

        // Retain the ID of the data item from hidden input element.
        dataItem.setId(Long.valueOf(dataItemId.getValue().toString()));

        // Save Dish.
        dishService.update(dataItem);

        return "set_dish_prices";
    }

    // Getters -----------------------------------------------------------------------------------

    public HtmlDataTable getDataTable() {
        return dataTable;
    }

    public Dish getDataItem() {
        return dataItem;
    }

    public HtmlInputHidden getDataItemId() {
        return dataItemId;
    }

    // Setters -----------------------------------------------------------------------------------

    public void setDataTable(HtmlDataTable dataTable) {
        this.dataTable = dataTable;
    }

    public void setDataItem(Dish dataItem) {
        this.dataItem = dataItem;
    }

    public void setDataItemId(HtmlInputHidden dataItemId) {
        this.dataItemId = dataItemId;
    }





    @PostConstruct
    private void init() {
        currentFoodCategory = foodCategoryService.findById(1L);
        dishesByFoodCategory = dishService.findByCategoryId(1L);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public FoodCategory getFoodCategory() {
        return foodCategory;
    }

    public void setFoodCategory(FoodCategory foodCategory) {
        this.foodCategory = foodCategory;
    }

    public boolean isKitchenMade() {
        return kitchenMade;
    }

    public void setKitchenMade(boolean kitchenMade) {
        this.kitchenMade = kitchenMade;
    }


    public List<Dish> getAllDishes() {
        if (updateNeeded) {
            allDishes = dishService.getAll();
            updateNeeded = false;
        }
        return allDishes;
    }

    public void setAllDishes(List<Dish> allDishes) {
        this.allDishes = allDishes;
    }

    public Dish getCurrentDish() {
        return currentDish;
    }

    public FoodCategory getCurrentFoodCategory() {
        return currentFoodCategory;
    }

    public List<Dish> getDishesByFoodCategory() {
        return dishesByFoodCategory;
    }

    public String getDishDetails(Long dishId) {
        this.currentDish = dishService.getById(dishId);
        return "dish_item";
    }

    public BigDecimal getCurrentDishPrice() {
        DishPrice dishPrice = dishPriceService.getLastActualDishPrice(currentDish, new Date());
        if (dishPrice != null) {
            Integer price = dishPrice.getPrice();
            return new BigDecimal(price).divide(new BigDecimal(100));
        }
        return BigDecimal.ZERO;
    }

    public void changeFoodCategory(Long currentFoodCategoryId) {
        currentFoodCategory = foodCategoryService.findById(currentFoodCategoryId);
        dishesByFoodCategory = dishService.findByCategoryId(currentFoodCategoryId);
    }

    public void addToCart(Long dishId) {
        cartBean.add(dishService.getById(dishId));
    }

    public BigDecimal getDishPrice(Long dishId) {
        Dish dish = dishService.getById(dishId);
        DishPrice dishPrice = dishPriceService.getLastActualDishPrice(dish, new Date());
        if (dishPrice != null) {
            Integer price = dishPrice.getPrice();
            return new BigDecimal(price).divide(new BigDecimal(100));
        }
        return BigDecimal.ZERO;
    }

    public String loadPageByFoodCategoryId(Long foodCategoryId) {
        currentFoodCategory = foodCategoryService.findById(foodCategoryId);
        dishesByFoodCategory = dishService.findByCategoryId(foodCategoryId);
        return "menu";
    }

    public List<Dish> getAll() {
        return dishService.getAll();
    }

    public String editAction(Dish dish) {
        dish.setEditable(true);
        return null;
    }

    public String delete(Long dishId) {
        dishService.delete(dishId);
        updateNeeded = true;
        return "";
    }

    public String createDish() {
        dishService.createDish(null, name, description, kitchenMade);
        name = null;
        description = null;
        kitchenMade = false;
        updateNeeded = true;
        return "";
    }

    public String saveAction() {
        for (Dish d : allDishes) {
            if (d.isEditable()) {
                dishService.update(d);
            }
        }
        updateNeeded = true;
        return null;
    }
}

src/main/java/com/bionic/sschudakov/web/FoodCategoryBean.java
package com.bionic.sschudakov.web;

import com.bionic.sschudakov.entity.FoodCategory;
import com.bionic.sschudakov.service.FoodCategoryService;
import org.openfaces.event.SelectionChangeEvent;
import org.springframework.context.annotation.Scope;

import javax.inject.Inject;
import javax.inject.Named;
import java.util.List;

@Named
@Scope("request")
public class FoodCategoryBean {

    private static int sCount = 0;

    @Inject
    private FoodCategoryService foodCategoryService;

    private String name;
    private String description;

    private List<FoodCategory> foodCategoriesList;

    private Long selectedFoodCategoryId = 0L;

    public FoodCategoryBean() {
        sCount++;
        System.out.println("FoodCategoryBean was created: " + sCount + " times");
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<FoodCategory> getFoodCategories() {
        return foodCategoryService.getAll();
    }

    public List<FoodCategory> getFoodCategoriesOrdered() {
        return foodCategoryService.getAllOrdered();
    }

    public void createFoodCategory() {
        foodCategoryService.createFoodCategory(name, description);
    }

    public void updateFoodCategory(FoodCategory foodCategory) {
        foodCategoryService.updateFoodCategory(foodCategory);
    }

    public FoodCategory getById(Long id) {
        return foodCategoryService.findById(id);
    }

    public void selectedFoodCategoryChanged(SelectionChangeEvent e) {
        System.out.println("" + e.getOldIndex() + " -> " + e.getNewIndex());
        int a = 0;

    }

    public void changeFoodCategoryIndex(Long foodCategoryId) {
        this.selectedFoodCategoryId = foodCategoryId;
    }

    public FoodCategory getSelectedFoodCategory() {
        return foodCategoryService.findById(selectedFoodCategoryId);
    }

}

src/main/java/com/bionic/sschudakov/web/RestaurantOrderBean.java
package com.bionic.sschudakov.web;

import com.bionic.sschudakov.dao.DishPriceDao;
import com.bionic.sschudakov.entity.Dish;
import com.bionic.sschudakov.entity.DishPrice;
import com.bionic.sschudakov.entity.OrderItem;
import com.bionic.sschudakov.entity.RestaurantOrder;
import com.bionic.sschudakov.service.OrderItemService;
import com.bionic.sschudakov.service.RestaurantOrderService;
import org.springframework.context.annotation.Scope;

import javax.inject.Inject;
import javax.inject.Named;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.*;

/**
 * Created by Sergey on 09.07.14.
 */
@Named
@Scope("request")
public class RestaurantOrderBean {

    @Inject
    private RestaurantOrderService restaurantOrderService;

    @Inject
    private OrderItemService orderItemService;

    @Inject
    private CartBean cartBean;

    private String orderNumber;

    private Date orderSubmitDate;

    public String getOrderNumber() {
        return orderNumber;
    }
    public Date getOrderSubmitDate() {
        return orderSubmitDate;
    }

    public String submitOrder(List<CartItem> cartItems, Date orderOpenDate, String clientsPhoneNumber) {

        if (clientsPhoneNumber == null || clientsPhoneNumber.equals("")) {
            return "no_phone_number";
        }

        if (cartItems.isEmpty()) {
            return "empty_cart";
        }

        orderSubmitDate = new Date();

        RestaurantOrder restaurantOrder = new RestaurantOrder();
        restaurantOrder.setDateTimeOpen(new Timestamp(orderOpenDate.getTime()));
        restaurantOrder.setDateTimeSubmit(new Timestamp(orderSubmitDate.getTime()));
        restaurantOrder.setComments(clientsPhoneNumber);

        String response = restaurantOrderService.createRestaurantOrder(restaurantOrder, cartItems);

        if (response.equals("error")) {
            return response;
        }

        // form order number.
        Calendar c = Calendar.getInstance();
        c.setTimeInMillis(orderSubmitDate.getTime());
        String yearNumber = Integer.toString(c.get(Calendar.YEAR)).substring(2);
        String orderId = restaurantOrder.getId().toString();
        while (orderId.length() < 4) {
            orderId = "0" + orderId;
        }

        orderNumber = yearNumber + orderId;

        cartBean.cleanCart();

        return response;

    }

    public Date getDeliveryDate() {
        Calendar c = Calendar.getInstance();
        c.setTimeInMillis(orderSubmitDate.getTime());
        c.add(Calendar.HOUR_OF_DAY, 2);
        c.set(Calendar.MINUTE, 0);
        c.set(Calendar.SECOND, 0);
        return c.getTime();
    }

}

src/main/webapp/e-kafe/contacts.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsf/composite"
                xmlns:o="http://openfaces.org/"
                xmlns:t="http://myfaces.apache.org/tomahawk"
                template="${request.contextPath}/e-kafe/templates/general.xhtml">

    <ui:define name="title"><h:outputText value="Welcome to E-kafe"/></ui:define>
    <ui:define name="header">
        <t:div styleClass="ekafe">
            <h:outputText value="E-kafe"/>
        </t:div>
        <t:div styleClass="headerText">
            <h:outputText value="Our menu"/>
        </t:div>
        <t:div styleClass="shoppingCart">
            <h:form id="headerCartInfo">
                <h:panelGrid columns="2">
                    <h:commandLink action="cart" styleClass="textLnk">
                        <h:graphicImage library="images" name="shopping_cart.png"/>
                    </h:commandLink>
                    <h:commandLink action="cart" styleClass="textLnk">
                        <h:panelGroup>
                            <h:outputText id="cartSizeHeader" value="#{cartBean.cartCount} item(s)"/><br/>
                            <h:outputText id="cartTotalPriceHeader" value="#{cartBean.cartTotalPrice} UAH">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText><br/>
                        </h:panelGroup></h:commandLink>
                </h:panelGrid>
            </h:form>
        </t:div>
    </ui:define>
    <ui:define name="content">

        <t:div style="margin: 50px auto; text-align: center">
            <h:outputText value="Phone Number for Orders:  +3 (756) 357 71 18" style="font-size: 28px; font-weight: bold"/>
        </t:div>

    </ui:define>

</ui:composition>

src/main/webapp/e-kafe/dish_item.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsf/composite"
                xmlns:o="http://openfaces.org/"
                xmlns:t="http://myfaces.apache.org/tomahawk"
                template="${request.contextPath}/e-kafe/templates/general.xhtml">

    <ui:define name="title"><h:outputText value="Welcome to E-kafe"/></ui:define>
    <ui:define name="header">
        <t:div styleClass="ekafe">
            <h:outputText value="E-kafe"/>
        </t:div>
        <t:div styleClass="headerText">
            <h:outputText value="Dish details"/>
        </t:div>
        <t:div styleClass="shoppingCart">
            <h:form id="headerCartInfo">
                <h:panelGrid columns="2">
                    <h:commandLink action="cart" styleClass="textLnk">
                        <h:graphicImage library="images" name="shopping_cart.png"/>
                    </h:commandLink>
                    <h:commandLink action="cart" styleClass="textLnk">
                        <h:panelGroup>
                            <h:outputText id="cartSizeHeader" value="#{cartBean.cartCount} item(s)"/><br/>
                            <h:outputText id="cartTotalPriceHeader" value="#{cartBean.cartTotalPrice} UAH">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText><br/>
                        </h:panelGroup></h:commandLink>
                </h:panelGrid>
            </h:form>
        </t:div>
    </ui:define>


    <ui:define name="content">

        <h:panelGroup layout="block" styleClass="centeredText">

            <h:outputText id="cartSize"
                          value="Your cart has #{cartBean.getCartItemCount(dishBean.currentDish.id)} item(s)"/><br/><br/>

            <h:outputText styleClass="dishName" value="#{dishBean.currentDish.name}"/><br/><br/>

            <h:graphicImage library="images" name="#{dishBean.currentDish.imgPath}" styleClass="dishImage"/><br/><br/>

            Food category:    #{dishBean.currentDish.foodCategory.name}<br/><br/>

            Description:    #{dishBean.currentDish.description}<br/><br/>

            Price: <h:outputText value="#{dishBean.currentDishPrice}">
            <f:convertNumber pattern="#0.00"/>
        </h:outputText> <br/><br/>

            <h:form id="newOrderItemForm">
                <!--input type="hidden" name="currentDishId" value="#{dishBean.currentDish.id}"/-->
                <h:commandButton value="Add to cart" action="#{dishBean.addToCart(dishBean.currentDish.id)}">
                    <f:ajax execute="@all" render=":cartSize :headerCartInfo:cartSizeHeader :headerCartInfo:cartTotalPriceHeader"/>
                </h:commandButton>
            </h:form><br/>


            <h:outputLink value="cart.xhtml">Go to Cart</h:outputLink><br/><br/>
        </h:panelGroup>


    </ui:define>


</ui:composition>

src/main/webapp/e-kafe/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsf/composite"
                xmlns:o="http://openfaces.org/"
                xmlns:t="http://myfaces.apache.org/tomahawk"
                template="${request.contextPath}/e-kafe/templates/general.xhtml">

    <ui:define name="title"><h:outputText value="Menu Page"/></ui:define>
    <ui:define name="header">
        <t:div styleClass="ekafe">
            <h:outputText value="E-kafe"/>
        </t:div>
        <t:div styleClass="headerText">
            <h:outputText value="Our menu"/>
        </t:div>
        <t:div styleClass="shoppingCart">
            <h:form id="headerCartInfo">
                <h:panelGrid columns="2">
                    <h:commandLink action="cart" styleClass="textLnk">
                        <h:graphicImage library="images" name="shopping_cart.png"/>
                    </h:commandLink>
                    <h:commandLink action="cart" styleClass="textLnk">
                        <h:panelGroup>
                            <h:outputText id="cartSizeHeader" value="#{cartBean.cartCount} item(s)"/><br/>
                            <h:outputText id="cartTotalPriceHeader" value="#{cartBean.cartTotalPrice} UAH">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText><br/>
                        </h:panelGroup></h:commandLink>
                </h:panelGrid>
            </h:form>
        </t:div>
    </ui:define>


    <ui:define name="content">
        <h:panelGrid styleClass="menuPanel" columns="2" columnClasses="menuNavigationPanel, dishPanel">
            <h:panelGroup layout="block">
                <h:form>

                    <ui:repeat value="#{foodCategoryBean.foodCategoriesOrdered}" var="f">
                        <h:commandLink value="#{f.name}" styleClass="foodCategoryLnk"
                                       action="#{dishBean.changeFoodCategory(f.id)}"/>
                        <br/>
                    </ui:repeat>
                </h:form>
            </h:panelGroup>
            <h:panelGroup layout="block">
               <t:div styleClass="dishNameMenu">
                   <h:outputText value="#{dishBean.currentFoodCategory.name}" style="padding: 5px; font-size: 16px;"/>
               </t:div>
                <h:form>
                    <h:dataTable id="dishesByFoodCategory"
                                 value="#{dishBean.dishesByFoodCategory}"
                                 var="d">
                        <h:column>
                            <f:facet name="header"/>
                            <h:graphicImage library="images" name="#{d.imgPath}"
                                            style="height: auto; width: 150px; margin-left: auto; margin-right: auto; padding: 0 20px 0 20px"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header"/>
                            <h:commandLink value="#{d.name}" action="#{dishBean.getDishDetails(d.id)}"
                                           style="padding: 0 20px 0 20px"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header"/>
                            <h:outputText value="#{d.description}" style="padding: 0 20px 0 20px"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header"/>
                            <h:outputText value="#{dishBean.getDishPrice(d.id)}" style="padding: 0 20px 0 20px">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText>
                            <h:outputText value="UAH     "/>
                        </h:column>
                        <h:column>
                            <f:facet name="header"/>

                            <h:commandButton value="Add to cart"
                                             action="#{dishBean.addToCart(d.id)}"
                                             style="margin: 0 20px">
                                <f:ajax execute="@all"
                                        render=":headerCartInfo:cartSizeHeader :headerCartInfo:cartTotalPriceHeader"/>
                            </h:commandButton>

                        </h:column>
                    </h:dataTable>
                </h:form>
            </h:panelGroup>
        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/e-kafe/order_submitted.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsf/composite"
                xmlns:o="http://openfaces.org/"
                xmlns:t="http://myfaces.apache.org/tomahawk"
                template="${request.contextPath}/e-kafe/templates/general.xhtml">

    <ui:define name="title"><h:outputText value="Welcome to E-kafe"/></ui:define>
    <ui:define name="header">
        <t:div styleClass="ekafe">
            <h:outputText value="E-kafe"/>
        </t:div>
        <t:div styleClass="headerText">
            <h:outputText value="Thank you!"/>
        </t:div>
        <t:div styleClass="shoppingCart">
            <h:form id="headerCartInfo">
                <h:panelGrid columns="2">
                    <h:commandLink action="cart" styleClass="textLnk">
                        <h:graphicImage library="images" name="shopping_cart.png"/>
                    </h:commandLink>
                    <h:commandLink action="cart" styleClass="textLnk">
                        <h:panelGroup>
                            <h:outputText id="cartSizeHeader" value="#{cartBean.cartCount} item(s)"/><br/>
                            <h:outputText id="cartTotalPriceHeader" value="#{cartBean.cartTotalPrice} UAH">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText><br/>
                        </h:panelGroup></h:commandLink>
                </h:panelGrid>
            </h:form>
        </t:div>
    </ui:define>

    <ui:define name="content">
        <t:div styleClass="centeredBlock">
            <t:div styleClass="note">
                <h:outputText value="Your order #" styleClass="submittedOrderText"/>
                <h:outputText value="#{restaurantOrderBean.orderNumber}" styleClass="submittedOrderText"
                              style="font-weight: bold"/>
                <h:outputText value=" from " styleClass="submittedOrderText"/>
                <h:outputText value="#{restaurantOrderBean.orderSubmitDate}" styleClass="submittedOrderText"
                              style="font-weight: bold">
                    <f:convertDateTime pattern="dd.MM.yyyy HH:mm"/>
                </h:outputText>
                <h:outputText value=" was successfully submitted!" styleClass="submittedOrderText"/><br/><br/><br/>

                <h:outputText value="It will be delivired by " styleClass="submittedOrderText"/>

                <h:outputText value="#{restaurantOrderBean.deliveryDate}" styleClass="submittedOrderText"
                              style="font-weight: bold">
                    <f:convertDateTime pattern="dd.MM.yyyy HH:mm"/>
                </h:outputText><br/><br/><br/>
                <h:outputText value="Bon Appetit!" styleClass="submittedOrderText"/><br/><br/><br/>
            </t:div>
            <h:graphicImage library="images" name="BonAppetit.png"
                            style="margin: 0 auto"/>
        </t:div>
    </ui:define>

</ui:composition>